/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as HeroRouteImport } from './routes/hero'
import { Route as ShareSlugRouteImport } from './routes/share/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroRoute = HeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/chat': typeof ChatRoute
  '/hero': typeof HeroRoute
  '/share/$slug': typeof ShareSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/chat': typeof ChatRoute
  '/hero': typeof HeroRoute
  '/share/$slug': typeof ShareSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/chat': typeof ChatRoute
  '/hero': typeof HeroRoute
  '/share/$slug': typeof ShareSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/chat' | '/hero' | '/share/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/chat' | '/hero' | '/share/$slug'
  id: '__root__' | '/' | '/app' | '/chat' | '/hero' | '/share/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ChatRoute: typeof ChatRoute
  HeroRoute: typeof HeroRoute
  ShareSlugRoute: typeof ShareSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero': {
      id: '/hero'
      path: '/hero'
      fullPath: '/hero'
      preLoaderRoute: typeof HeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ChatRoute: ChatRoute,
  HeroRoute: HeroRoute,
  ShareSlugRoute: ShareSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
